// Copies the desk's markdown (generated by Claude Code at the repo root) into
// web/content/ so the Next app can read it at build time. Runs automatically on
// `predev` and `prebuild`. Resolves paths relative to this script, so it works
// regardless of the current working directory (local or Vercel).
//
// Non-destructive by design: a source folder is only refreshed if it exists. On
// Vercel (CLI deploy), the repo-root sources aren't in the upload, so the
// content/ already uploaded with the deploy is left intact rather than wiped.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.join(here, "..");
const repoRoot = path.join(webRoot, "..");
const contentDir = path.join(webRoot, "content");

// source dir at repo root -> destination name under web/content/
const MAP = {
  briefings: "briefings",
  learning: "learning",
  strategy: "strategy",
  creative: "creative",
  profile: "profile",
  answers: "answers",
};

fs.mkdirSync(contentDir, { recursive: true });

let refreshed = 0;
let kept = 0;
for (const [src, dest] of Object.entries(MAP)) {
  const from = path.join(repoRoot, src);
  const to = path.join(contentDir, dest);
  if (!fs.existsSync(from)) {
    kept += 1; // keep whatever was uploaded with the deploy
    continue;
  }
  fs.rmSync(to, { recursive: true, force: true });
  fs.cpSync(from, to, { recursive: true });
  refreshed += 1;
}

console.log(`[sync-content] refreshed ${refreshed} source folder(s); kept ${kept} as-is`);
