// Copies the desk's markdown (generated by Claude Code at the repo root) into
// web/content/ so the Next app can read it at build time. Runs automatically on
// `predev` and `prebuild`. Resolves paths relative to this script, so it works
// regardless of the current working directory (local or Vercel).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.join(here, "..");
const repoRoot = path.join(webRoot, "..");
const contentDir = path.join(webRoot, "content");

// source dir at repo root -> destination name under web/content/
const MAP = {
  briefings: "briefings",
  learning: "learning",
  strategy: "strategy",
  profile: "profile",
};

function reset(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
}

reset(contentDir);

let copied = 0;
for (const [src, dest] of Object.entries(MAP)) {
  const from = path.join(repoRoot, src);
  const to = path.join(contentDir, dest);
  if (!fs.existsSync(from)) {
    console.warn(`[sync-content] skip (missing): ${src}`);
    continue;
  }
  fs.cpSync(from, to, { recursive: true });
  copied += 1;
}

console.log(`[sync-content] synced ${copied} source folder(s) into web/content/`);
